# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'door2.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GlassCalc(object):
    def setupUi(self, GlassCalc):
        GlassCalc.setObjectName("GlassCalc")
        GlassCalc.resize(1150, 766)
        self.centralwidget = QtWidgets.QWidget(GlassCalc)
        self.centralwidget.setObjectName("centralwidget")
        self.label_01 = QtWidgets.QLabel(self.centralwidget)
        self.label_01.setGeometry(QtCore.QRect(10, 40, 151, 31))
        self.label_01.setObjectName("label_01")
        self.label_02 = QtWidgets.QLabel(self.centralwidget)
        self.label_02.setGeometry(QtCore.QRect(10, 10, 151, 31))
        self.label_02.setObjectName("label_02")
        self.label_03 = QtWidgets.QLabel(self.centralwidget)
        self.label_03.setGeometry(QtCore.QRect(10, 70, 151, 31))
        self.label_03.setObjectName("label_03")
        self.label_05 = QtWidgets.QLabel(self.centralwidget)
        self.label_05.setGeometry(QtCore.QRect(10, 110, 41, 31))
        self.label_05.setObjectName("label_05")
        self.label_06 = QtWidgets.QLabel(self.centralwidget)
        self.label_06.setGeometry(QtCore.QRect(10, 140, 81, 31))
        self.label_06.setObjectName("label_06")
        self.label_08 = QtWidgets.QLabel(self.centralwidget)
        self.label_08.setGeometry(QtCore.QRect(10, 200, 91, 31))
        self.label_08.setObjectName("label_08")
        self.label_09 = QtWidgets.QLabel(self.centralwidget)
        self.label_09.setGeometry(QtCore.QRect(10, 260, 151, 31))
        self.label_09.setObjectName("label_09")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(10, 290, 111, 31))
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(10, 310, 31, 31))
        self.label_13.setObjectName("label_13")
        self.label_07 = QtWidgets.QLabel(self.centralwidget)
        self.label_07.setGeometry(QtCore.QRect(10, 170, 101, 31))
        self.label_07.setObjectName("label_07")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(10, 230, 151, 31))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(10, 350, 51, 31))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(10, 380, 111, 31))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(10, 410, 111, 31))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(10, 440, 111, 31))
        self.label_18.setObjectName("label_18")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(10, 601, 51, 20))
        self.label_21.setObjectName("label_21")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(50, 600, 101, 21))
        self.label_23.setObjectName("label_23")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(10, 500, 131, 22))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 520, 171, 22))
        self.checkBox_2.setObjectName("checkBox_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 570, 61, 27))
        self.pushButton.setObjectName("pushButton")
        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setGeometry(QtCore.QRect(130, 110, 151, 27))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_6 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_6.setGeometry(QtCore.QRect(130, 140, 151, 27))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_7 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_7.setGeometry(QtCore.QRect(130, 170, 151, 27))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_8 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_8.setGeometry(QtCore.QRect(130, 200, 151, 27))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_9 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_9.setGeometry(QtCore.QRect(130, 230, 151, 27))
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_10 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_10.setGeometry(QtCore.QRect(130, 260, 151, 27))
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_11 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_11.setGeometry(QtCore.QRect(130, 290, 151, 27))
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_14 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_14.setGeometry(QtCore.QRect(130, 320, 151, 27))
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_15 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_15.setGeometry(QtCore.QRect(130, 350, 151, 27))
        self.comboBox_15.setObjectName("comboBox_15")
        self.comboBox_16 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_16.setGeometry(QtCore.QRect(130, 380, 151, 27))
        self.comboBox_16.setObjectName("comboBox_16")
        self.comboBox_17 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_17.setGeometry(QtCore.QRect(130, 410, 151, 27))
        self.comboBox_17.setObjectName("comboBox_17")
        self.comboBox_18 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_18.setGeometry(QtCore.QRect(130, 440, 151, 27))
        self.comboBox_18.setObjectName("comboBox_18")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(590, 600, 71, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(710, 600, 71, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(550, 600, 61, 21))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(670, 600, 61, 21))
        self.label_20.setObjectName("label_20")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(550, 620, 61, 21))
        self.label_25.setObjectName("label_25")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(590, 620, 71, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(710, 620, 71, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(670, 620, 61, 21))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(480, 600, 71, 21))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(480, 620, 71, 21))
        self.label_28.setObjectName("label_28")
        self.comboBox_13 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_13.setGeometry(QtCore.QRect(280, 140, 151, 27))
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_19 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_19.setGeometry(QtCore.QRect(280, 170, 151, 27))
        self.comboBox_19.setObjectName("comboBox_19")
        self.comboBox_20 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_20.setGeometry(QtCore.QRect(280, 200, 151, 27))
        self.comboBox_20.setObjectName("comboBox_20")
        self.comboBox_21 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_21.setGeometry(QtCore.QRect(280, 230, 151, 27))
        self.comboBox_21.setObjectName("comboBox_21")
        self.comboBox_22 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_22.setGeometry(QtCore.QRect(280, 260, 151, 27))
        self.comboBox_22.setObjectName("comboBox_22")
        self.comboBox_23 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_23.setGeometry(QtCore.QRect(280, 290, 151, 27))
        self.comboBox_23.setObjectName("comboBox_23")
        self.comboBox_25 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_25.setGeometry(QtCore.QRect(280, 320, 151, 27))
        self.comboBox_25.setObjectName("comboBox_25")
        self.comboBox_26 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_26.setGeometry(QtCore.QRect(280, 350, 151, 27))
        self.comboBox_26.setObjectName("comboBox_26")
        self.comboBox_27 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_27.setGeometry(QtCore.QRect(280, 380, 151, 27))
        self.comboBox_27.setObjectName("comboBox_27")
        self.comboBox_28 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_28.setGeometry(QtCore.QRect(280, 410, 151, 27))
        self.comboBox_28.setObjectName("comboBox_28")
        self.comboBox_29 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_29.setGeometry(QtCore.QRect(280, 440, 151, 27))
        self.comboBox_29.setObjectName("comboBox_29")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(10, 470, 111, 31))
        self.label_29.setObjectName("label_29")
        self.comboBox_30 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_30.setGeometry(QtCore.QRect(130, 470, 151, 27))
        self.comboBox_30.setObjectName("comboBox_30")
        self.comboBox_31 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_31.setGeometry(QtCore.QRect(280, 470, 151, 27))
        self.comboBox_31.setObjectName("comboBox_31")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(130, 40, 81, 31))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(210, 40, 81, 31))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(130, 10, 51, 31))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_4.setGeometry(QtCore.QRect(210, 10, 51, 31))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_5.setGeometry(QtCore.QRect(130, 70, 91, 31))
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_6.setGeometry(QtCore.QRect(210, 70, 131, 31))
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_7 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_7.setGeometry(QtCore.QRect(50, 260, 41, 31))
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_8 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_8.setGeometry(QtCore.QRect(90, 260, 41, 31))
        self.radioButton_8.setObjectName("radioButton_8")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 620, 421, 81))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(70, 570, 61, 27))
        self.pushButton_2.setObjectName("pushButton_2")
        self.radioButton_9 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_9.setGeometry(QtCore.QRect(10, 330, 41, 21))
        self.radioButton_9.setObjectName("radioButton_9")
        self.radioButton_10 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_10.setGeometry(QtCore.QRect(40, 330, 41, 20))
        self.radioButton_10.setObjectName("radioButton_10")
        self.radioButton_11 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_11.setGeometry(QtCore.QRect(70, 330, 41, 20))
        self.radioButton_11.setObjectName("radioButton_11")
        self.comboBox_32 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_32.setGeometry(QtCore.QRect(10, 540, 121, 27))
        self.comboBox_32.setObjectName("comboBox_32")
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(1030, 700, 101, 21))
        self.label_34.setObjectName("label_34")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(440, 640, 101, 22))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(440, 660, 101, 22))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_5.setGeometry(QtCore.QRect(440, 680, 111, 22))
        self.checkBox_5.setObjectName("checkBox_5")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(590, 640, 71, 21))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(710, 640, 71, 21))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(590, 660, 71, 21))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(710, 660, 71, 21))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(590, 680, 71, 21))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_10.setGeometry(QtCore.QRect(710, 680, 71, 21))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(670, 640, 61, 21))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(670, 660, 61, 21))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(670, 680, 61, 21))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(550, 640, 61, 21))
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(550, 660, 61, 21))
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(550, 680, 61, 21))
        self.label_41.setObjectName("label_41")
        self.radioButton_12 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_12.setGeometry(QtCore.QRect(340, 70, 61, 31))
        self.radioButton_12.setObjectName("radioButton_12")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(790, 600, 101, 21))
        self.label_35.setObjectName("label_35")
        self.comboBox_33 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_33.setGeometry(QtCore.QRect(790, 620, 101, 21))
        self.comboBox_33.setObjectName("comboBox_33")
        self.comboBox_34 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_34.setGeometry(QtCore.QRect(790, 640, 101, 21))
        self.comboBox_34.setObjectName("comboBox_34")
        self.comboBox_35 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_35.setGeometry(QtCore.QRect(790, 660, 101, 21))
        self.comboBox_35.setObjectName("comboBox_35")
        self.label_42 = QtWidgets.QLabel(self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(1010, 600, 71, 21))
        self.label_42.setObjectName("label_42")
        self.comboBox_36 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_36.setGeometry(QtCore.QRect(790, 680, 101, 21))
        self.comboBox_36.setObjectName("comboBox_36")
        self.comboBox_37 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_37.setGeometry(QtCore.QRect(890, 620, 101, 21))
        self.comboBox_37.setObjectName("comboBox_37")
        self.comboBox_38 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_38.setGeometry(QtCore.QRect(890, 640, 101, 21))
        self.comboBox_38.setObjectName("comboBox_38")
        self.label_43 = QtWidgets.QLabel(self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(1100, 600, 21, 21))
        self.label_43.setObjectName("label_43")
        self.comboBox_39 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_39.setGeometry(QtCore.QRect(890, 660, 101, 21))
        self.comboBox_39.setObjectName("comboBox_39")
        self.comboBox_40 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_40.setGeometry(QtCore.QRect(890, 680, 101, 21))
        self.comboBox_40.setObjectName("comboBox_40")
        self.comboBox_41 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_41.setGeometry(QtCore.QRect(990, 620, 101, 21))
        self.comboBox_41.setObjectName("comboBox_41")
        self.comboBox_42 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_42.setGeometry(QtCore.QRect(990, 640, 101, 21))
        self.comboBox_42.setObjectName("comboBox_42")
        self.comboBox_43 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_43.setGeometry(QtCore.QRect(990, 660, 101, 21))
        self.comboBox_43.setObjectName("comboBox_43")
        self.comboBox_44 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_44.setGeometry(QtCore.QRect(990, 680, 101, 21))
        self.comboBox_44.setObjectName("comboBox_44")
        self.label_44 = QtWidgets.QLabel(self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(890, 600, 101, 21))
        self.label_44.setObjectName("label_44")
        self.comboBox_45 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_45.setGeometry(QtCore.QRect(1090, 620, 41, 21))
        self.comboBox_45.setObjectName("comboBox_45")
        self.comboBox_46 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_46.setGeometry(QtCore.QRect(1090, 640, 41, 21))
        self.comboBox_46.setObjectName("comboBox_46")
        self.comboBox_47 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_47.setGeometry(QtCore.QRect(1090, 660, 41, 21))
        self.comboBox_47.setObjectName("comboBox_47")
        self.comboBox_48 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_48.setGeometry(QtCore.QRect(1090, 680, 41, 21))
        self.comboBox_48.setObjectName("comboBox_48")
        GlassCalc.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GlassCalc)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1150, 21))
        self.menubar.setObjectName("menubar")
        GlassCalc.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GlassCalc)
        self.statusbar.setAcceptDrops(False)
        self.statusbar.setObjectName("statusbar")
        GlassCalc.setStatusBar(self.statusbar)

        self.retranslateUi(GlassCalc)
        QtCore.QMetaObject.connectSlotsByName(GlassCalc)

    def retranslateUi(self, GlassCalc):
        _translate = QtCore.QCoreApplication.translate
        GlassCalc.setWindowTitle(_translate("GlassCalc", "GlassCalc 1"))
        self.label_01.setText(_translate("GlassCalc", "сторона открывания"))
        self.label_02.setText(_translate("GlassCalc", "к-во створок"))
        self.label_03.setText(_translate("GlassCalc", "тип ручки"))
        self.label_05.setText(_translate("GlassCalc", "стекло"))
        self.label_06.setText(_translate("GlassCalc", "нижний фитинг"))
        self.label_08.setText(_translate("GlassCalc", "верхний фитинг"))
        self.label_09.setText(_translate("GlassCalc", "петли"))
        self.label_11.setText(_translate("GlassCalc", "нажимной гарнитур"))
        self.label_13.setText(_translate("GlassCalc", "замок"))
        self.label_07.setText(_translate("GlassCalc", "крепление фитинга"))
        self.label_14.setText(_translate("GlassCalc", "крепление фитинга"))
        self.label_15.setText(_translate("GlassCalc", "ответка"))
        self.label_16.setText(_translate("GlassCalc", "уплотнит низ"))
        self.label_17.setText(_translate("GlassCalc", "уплотнит боков."))
        self.label_18.setText(_translate("GlassCalc", "уплотнит верх"))
        self.label_21.setText(_translate("GlassCalc", "Итого:"))
        self.label_23.setText(_translate("GlassCalc", "цена"))
        self.checkBox.setText(_translate("GlassCalc", "установка"))
        self.checkBox_2.setText(_translate("GlassCalc", "установка доводчика"))
        self.pushButton.setText(_translate("GlassCalc", "расчет"))
        self.label_19.setText(_translate("GlassCalc", "ширина"))
        self.label_20.setText(_translate("GlassCalc", "высота"))
        self.label_25.setText(_translate("GlassCalc", "ширина"))
        self.label_26.setText(_translate("GlassCalc", "высота"))
        self.label_27.setText(_translate("GlassCalc", "1 створка"))
        self.label_28.setText(_translate("GlassCalc", "2 створка"))
        self.label_29.setText(_translate("GlassCalc", "уплотнит петлевой"))
        self.radioButton.setText(_translate("GlassCalc", "левая"))
        self.radioButton_2.setText(_translate("GlassCalc", "правая"))
        self.radioButton_3.setText(_translate("GlassCalc", "1"))
        self.radioButton_4.setText(_translate("GlassCalc", "2"))
        self.radioButton_5.setText(_translate("GlassCalc", "Офисная"))
        self.radioButton_6.setText(_translate("GlassCalc", "Нажимной гарнитур"))
        self.radioButton_7.setText(_translate("GlassCalc", "2"))
        self.radioButton_8.setText(_translate("GlassCalc", "3"))
        self.pushButton_2.setText(_translate("GlassCalc", "сохр."))
        self.radioButton_9.setText(_translate("GlassCalc", "н"))
        self.radioButton_10.setText(_translate("GlassCalc", "с"))
        self.radioButton_11.setText(_translate("GlassCalc", "в"))
        self.label_34.setText(_translate("GlassCalc", "mitinva1@gmail.com"))
        self.checkBox_3.setText(_translate("GlassCalc", "глушняк сверху "))
        self.checkBox_4.setText(_translate("GlassCalc", "глушняк справа "))
        self.checkBox_5.setText(_translate("GlassCalc", "глушняк слева   "))
        self.label_36.setText(_translate("GlassCalc", "высота"))
        self.label_37.setText(_translate("GlassCalc", "высота"))
        self.label_38.setText(_translate("GlassCalc", "высота"))
        self.label_39.setText(_translate("GlassCalc", "ширина"))
        self.label_40.setText(_translate("GlassCalc", "ширина"))
        self.label_41.setText(_translate("GlassCalc", "ширина"))
        self.radioButton_12.setText(_translate("GlassCalc", "кноб"))
        self.label_35.setText(_translate("GlassCalc", "зажимной профиль"))
        self.label_42.setText(_translate("GlassCalc", "коннекторы"))
        self.label_43.setText(_translate("GlassCalc", "к-во"))
        self.label_44.setText(_translate("GlassCalc", "крышки профиля"))


