# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'door.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1112, 752)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_01 = QtWidgets.QLabel(self.centralwidget)
        self.label_01.setGeometry(QtCore.QRect(10, 40, 151, 31))
        self.label_01.setObjectName("label_01")
        self.label_02 = QtWidgets.QLabel(self.centralwidget)
        self.label_02.setGeometry(QtCore.QRect(10, 10, 151, 31))
        self.label_02.setObjectName("label_02")
        self.label_03 = QtWidgets.QLabel(self.centralwidget)
        self.label_03.setGeometry(QtCore.QRect(10, 70, 151, 31))
        self.label_03.setObjectName("label_03")
        self.label_04 = QtWidgets.QLabel(self.centralwidget)
        self.label_04.setGeometry(QtCore.QRect(10, 100, 151, 31))
        self.label_04.setObjectName("label_04")
        self.label_05 = QtWidgets.QLabel(self.centralwidget)
        self.label_05.setGeometry(QtCore.QRect(10, 130, 151, 31))
        self.label_05.setObjectName("label_05")
        self.label_06 = QtWidgets.QLabel(self.centralwidget)
        self.label_06.setGeometry(QtCore.QRect(10, 170, 151, 31))
        self.label_06.setObjectName("label_06")
        self.label_08 = QtWidgets.QLabel(self.centralwidget)
        self.label_08.setGeometry(QtCore.QRect(10, 230, 151, 31))
        self.label_08.setObjectName("label_08")
        self.label_09 = QtWidgets.QLabel(self.centralwidget)
        self.label_09.setGeometry(QtCore.QRect(10, 290, 151, 31))
        self.label_09.setObjectName("label_09")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(10, 320, 151, 31))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(10, 350, 151, 31))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(10, 380, 151, 31))
        self.label_13.setObjectName("label_13")
        self.label_07 = QtWidgets.QLabel(self.centralwidget)
        self.label_07.setGeometry(QtCore.QRect(10, 200, 151, 31))
        self.label_07.setObjectName("label_07")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(10, 260, 151, 31))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(10, 410, 151, 31))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(10, 440, 151, 31))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(10, 470, 151, 31))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(10, 500, 151, 31))
        self.label_18.setObjectName("label_18")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(10, 630, 51, 31))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(90, 630, 281, 31))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(90, 650, 291, 31))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(90, 670, 291, 31))
        self.label_24.setObjectName("label_24")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(10, 560, 131, 22))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 580, 171, 22))
        self.checkBox_2.setObjectName("checkBox_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 600, 93, 27))
        self.pushButton.setObjectName("pushButton")
        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setGeometry(QtCore.QRect(150, 130, 121, 27))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_6 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_6.setGeometry(QtCore.QRect(150, 170, 121, 27))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_7 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_7.setGeometry(QtCore.QRect(150, 200, 121, 27))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_8 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_8.setGeometry(QtCore.QRect(150, 230, 121, 27))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_9 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_9.setGeometry(QtCore.QRect(150, 260, 121, 27))
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_10 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_10.setGeometry(QtCore.QRect(150, 290, 121, 27))
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_11 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_11.setGeometry(QtCore.QRect(150, 320, 121, 27))
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_12 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_12.setGeometry(QtCore.QRect(150, 350, 121, 27))
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_14 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_14.setGeometry(QtCore.QRect(150, 380, 121, 27))
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_15 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_15.setGeometry(QtCore.QRect(150, 410, 121, 27))
        self.comboBox_15.setObjectName("comboBox_15")
        self.comboBox_16 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_16.setGeometry(QtCore.QRect(150, 440, 121, 27))
        self.comboBox_16.setObjectName("comboBox_16")
        self.comboBox_17 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_17.setGeometry(QtCore.QRect(150, 470, 121, 27))
        self.comboBox_17.setObjectName("comboBox_17")
        self.comboBox_18 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_18.setGeometry(QtCore.QRect(150, 500, 121, 27))
        self.comboBox_18.setObjectName("comboBox_18")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(780, 580, 113, 27))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(980, 580, 113, 27))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(710, 580, 61, 31))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(900, 580, 61, 31))
        self.label_20.setObjectName("label_20")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(710, 610, 61, 31))
        self.label_25.setObjectName("label_25")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(780, 610, 113, 27))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(980, 610, 113, 27))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(900, 610, 61, 31))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(630, 580, 71, 31))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(630, 610, 71, 31))
        self.label_28.setObjectName("label_28")
        self.comboBox_13 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_13.setGeometry(QtCore.QRect(270, 170, 121, 27))
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_19 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_19.setGeometry(QtCore.QRect(270, 200, 121, 27))
        self.comboBox_19.setObjectName("comboBox_19")
        self.comboBox_20 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_20.setGeometry(QtCore.QRect(270, 230, 121, 27))
        self.comboBox_20.setObjectName("comboBox_20")
        self.comboBox_21 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_21.setGeometry(QtCore.QRect(270, 260, 121, 27))
        self.comboBox_21.setObjectName("comboBox_21")
        self.comboBox_22 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_22.setGeometry(QtCore.QRect(270, 290, 121, 27))
        self.comboBox_22.setObjectName("comboBox_22")
        self.comboBox_23 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_23.setGeometry(QtCore.QRect(270, 320, 121, 27))
        self.comboBox_23.setObjectName("comboBox_23")
        self.comboBox_24 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_24.setGeometry(QtCore.QRect(270, 350, 121, 27))
        self.comboBox_24.setObjectName("comboBox_24")
        self.comboBox_25 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_25.setGeometry(QtCore.QRect(270, 380, 121, 27))
        self.comboBox_25.setObjectName("comboBox_25")
        self.comboBox_26 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_26.setGeometry(QtCore.QRect(270, 410, 121, 27))
        self.comboBox_26.setObjectName("comboBox_26")
        self.comboBox_27 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_27.setGeometry(QtCore.QRect(270, 440, 121, 27))
        self.comboBox_27.setObjectName("comboBox_27")
        self.comboBox_28 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_28.setGeometry(QtCore.QRect(270, 470, 121, 27))
        self.comboBox_28.setObjectName("comboBox_28")
        self.comboBox_29 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_29.setGeometry(QtCore.QRect(270, 500, 121, 27))
        self.comboBox_29.setObjectName("comboBox_29")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(10, 530, 151, 31))
        self.label_29.setObjectName("label_29")
        self.comboBox_30 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_30.setGeometry(QtCore.QRect(150, 530, 121, 27))
        self.comboBox_30.setObjectName("comboBox_30")
        self.comboBox_31 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_31.setGeometry(QtCore.QRect(270, 530, 121, 27))
        self.comboBox_31.setObjectName("comboBox_31")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(150, 40, 81, 31))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(240, 40, 81, 31))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(150, 10, 41, 31))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_4.setGeometry(QtCore.QRect(240, 10, 51, 31))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_5.setGeometry(QtCore.QRect(150, 70, 91, 31))
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_6.setGeometry(QtCore.QRect(240, 70, 161, 31))
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_7 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_7.setGeometry(QtCore.QRect(50, 290, 41, 31))
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_8 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_8.setGeometry(QtCore.QRect(90, 290, 41, 31))
        self.radioButton_8.setObjectName("radioButton_8")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(280, 570, 291, 131))
        self.textBrowser.setObjectName("textBrowser")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(400, 170, 51, 31))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(400, 200, 51, 31))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(400, 230, 51, 31))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(400, 260, 51, 31))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(400, 290, 51, 31))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(400, 320, 51, 31))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(400, 350, 51, 31))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(400, 380, 51, 31))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(400, 410, 51, 31))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(400, 440, 51, 31))
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(400, 470, 51, 31))
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(400, 500, 51, 31))
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(400, 530, 51, 31))
        self.label_42.setObjectName("label_42")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(430, 10, 671, 541))
        self.graphicsView.setObjectName("graphicsView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1112, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_01.setText(_translate("MainWindow", "сторона открывания"))
        self.label_02.setText(_translate("MainWindow", "к-во створок"))
        self.label_03.setText(_translate("MainWindow", "тип ручки"))
        self.label_04.setText(_translate("MainWindow", "установка"))
        self.label_05.setText(_translate("MainWindow", "стекло"))
        self.label_06.setText(_translate("MainWindow", "нижний фитинг"))
        self.label_08.setText(_translate("MainWindow", "верхний фитинг"))
        self.label_09.setText(_translate("MainWindow", "петли"))
        self.label_11.setText(_translate("MainWindow", "нажимной гарнитур"))
        self.label_12.setText(_translate("MainWindow", "офисная ручка"))
        self.label_13.setText(_translate("MainWindow", "замок"))
        self.label_07.setText(_translate("MainWindow", "крепление фитинга"))
        self.label_14.setText(_translate("MainWindow", "крепление фитинга"))
        self.label_15.setText(_translate("MainWindow", "ответка"))
        self.label_16.setText(_translate("MainWindow", "уплотнит низ"))
        self.label_17.setText(_translate("MainWindow", "уплотнит боков."))
        self.label_18.setText(_translate("MainWindow", "уплотнит верх"))
        self.label_21.setText(_translate("MainWindow", "Итого:"))
        self.label_22.setText(_translate("MainWindow", "м.кв"))
        self.label_23.setText(_translate("MainWindow", "цена"))
        self.label_24.setText(_translate("MainWindow", "цена с установкой"))
        self.checkBox.setText(_translate("MainWindow", "установка"))
        self.checkBox_2.setText(_translate("MainWindow", "установка доводчика"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.label_19.setText(_translate("MainWindow", "ширина"))
        self.label_20.setText(_translate("MainWindow", "высота"))
        self.label_25.setText(_translate("MainWindow", "ширина"))
        self.label_26.setText(_translate("MainWindow", "высота"))
        self.label_27.setText(_translate("MainWindow", "1 створка"))
        self.label_28.setText(_translate("MainWindow", "2 створка"))
        self.label_29.setText(_translate("MainWindow", "уплотнит петлевой"))
        self.radioButton.setText(_translate("MainWindow", "левая"))
        self.radioButton_2.setText(_translate("MainWindow", "правая"))
        self.radioButton_3.setText(_translate("MainWindow", "1"))
        self.radioButton_4.setText(_translate("MainWindow", "2"))
        self.radioButton_5.setText(_translate("MainWindow", "Офисная"))
        self.radioButton_6.setText(_translate("MainWindow", "Нажимной гарнитур"))
        self.radioButton_7.setText(_translate("MainWindow", "2"))
        self.radioButton_8.setText(_translate("MainWindow", "3"))
        self.label_30.setText(_translate("MainWindow", "!"))
        self.label_31.setText(_translate("MainWindow", "!"))
        self.label_32.setText(_translate("MainWindow", "!"))
        self.label_33.setText(_translate("MainWindow", "!"))
        self.label_34.setText(_translate("MainWindow", "!"))
        self.label_35.setText(_translate("MainWindow", "!"))
        self.label_36.setText(_translate("MainWindow", "!"))
        self.label_37.setText(_translate("MainWindow", "!"))
        self.label_38.setText(_translate("MainWindow", "!"))
        self.label_39.setText(_translate("MainWindow", "!"))
        self.label_40.setText(_translate("MainWindow", "!"))
        self.label_41.setText(_translate("MainWindow", "!"))
        self.label_42.setText(_translate("MainWindow", "!"))

